vim.g.mapleader = " "
vim.keymap.set("n", "<Esc>", "<cmd>nohlsearch<CR>")
vim.keymap.set("n", "<leader>e", vim.diagnostic.open_float, {})
vim.keymap.set("n", "<leader>V", vim.cmd.vsplit)
vim.keymap.set("n", "<leader>H", vim.cmd.split)
vim.keymap.set("n", "<leader>v", function()
    vim.cmd.vsplit()
    vim.cmd.wincmd("l")
end)
vim.keymap.set("n", "<leader>h", function()
    vim.cmd.split()
    vim.cmd.wincmd("j")
end)
